apiVersion: v1
kind: Secret
metadata:
  name: muchtodo-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://USERNAME:PASSWORD@starttech-mongodb.rzkfg9p.mongodb.net/?appName=starttech-mongodb"
  JWT_SECRET_KEY: "your-super-secret-key"